INSERT INTO movie_db.movie (name, rating, release_year) VALUES
                                                   ('Inception', 8.8, 2010),
                                                   ('The Dark Knight', 9.0, 2008),
                                                   ('Interstellar', 8.6, 2014),
                                                   ('The Matrix', 8.7, 1999),
                                                   ('Pulp Fiction', 8.9, 1994),
                                                   ('Forrest Gump', 8.8, 1994),
                                                   ('The Shawshank Redemption', 9.3, 1994),
                                                   ('The Godfather', 9.2, 1972),
                                                   ('The Godfather: Part II', 9.0, 1974),
                                                   ('Fight Club', 8.8, 1999),
                                                   ('The Lord of the Rings: The Fellowship of the Ring', 8.8, 2001),
                                                   ('The Lord of the Rings: The Two Towers', 8.7, 2002),
                                                   ('The Lord of the Rings: The Return of the King', 9.0, 2003),
                                                   ('Gladiator', 8.5, 2000),
                                                   ('Braveheart', 8.3, 1995),
                                                   ('The Avengers', 8.0, 2012),
                                                   ('Avengers: Endgame', 8.4, 2019),
                                                   ('The Lion King', 8.5, 1994),
                                                   ('Star Wars: Episode IV - A New Hope', 8.6, 1977),
                                                   ('Star Wars: Episode V - The Empire Strikes Back', 8.7, 1980),
                                                   ('Jurassic Park', 8.1, 1993),
                                                   ('The Terminator', 8.0, 1984),
                                                   ('Terminator 2: Judgment Day', 8.5, 1991),
                                                   ('Back to the Future', 8.5, 1985),
                                                   ('Toy Story', 8.3, 1995),
                                                   ('Schindler’s List', 8.9, 1993),
                                                   ('Saving Private Ryan', 8.6, 1998),
                                                   ('Se7en', 8.6, 1995),
                                                   ('The Silence of the Lambs', 8.6, 1991),
                                                   ('Django Unchained', 8.4, 2012);
INSERT INTO movie_db.actor (name, age) VALUES
                                  ('Leonardo DiCaprio', 49),
                                  ('Christian Bale', 50),
                                  ('Matthew McConaughey', 54),
                                  ('Keanu Reeves', 59),
                                  ('John Travolta', 70),
                                  ('Tom Hanks', 68),
                                  ('Morgan Freeman', 87),
                                  ('Marlon Brando', 80),
                                  ('Robert De Niro', 81),
                                  ('Edward Norton', 54),
                                  ('Elijah Wood', 43),
                                  ('Viggo Mortensen', 66),
                                  ('Orlando Bloom', 47),
                                  ('Russell Crowe', 59),
                                  ('Mel Gibson', 68),
                                  ('Robert Downey Jr.', 59),
                                  ('Chris Hemsworth', 41),
                                  ('James Earl Jones', 93),
                                  ('Mark Hamill', 73),
                                  ('Harrison Ford', 82),
                                  ('Sam Neill', 77),
                                  ('Arnold Schwarzenegger', 77),
                                  ('Linda Hamilton', 68),
                                  ('Michael J. Fox', 63),
                                  ('Tom Hanks', 68),
                                  ('Liam Neeson', 72),
                                  ('Tom Cruise', 62),
                                  ('Brad Pitt', 60),
                                  ('Anthony Hopkins', 86),
                                  ('Jamie Foxx', 57);
INSERT INTO movie_db.movie_actor (movie_id, actor_id) VALUES
                                                 (1, 1), (1, 5), (2, 2), (2, 10), (3, 3),
                                                 (3, 17), (4, 4), (4, 11), (5, 5), (5, 9),
                                                 (6, 6), (6, 7), (7, 7), (8, 8), (8, 9),
                                                 (9, 8), (9, 9), (10, 10), (10, 12), (11, 11),
                                                 (11, 13), (12, 11), (12, 14), (13, 11), (13, 15),
                                                 (14, 14), (14, 2), (15, 15), (15, 16), (16, 17),
                                                 (16, 18), (17, 17), (17, 19), (18, 18), (18, 20),
                                                 (19, 19), (19, 21), (20, 19), (20, 22), (21, 20),
                                                 (21, 23), (22, 21), (22, 24), (23, 22), (23, 24),
                                                 (24, 24), (25, 25), (25, 1), (26, 26), (26, 2),
                                                 (27, 27), (27, 10), (28, 28), (28, 12), (29, 29),
                                                 (29, 4), (30, 30), (30, 6);


